# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd8c1ba2269e3645258a11d15d902c1c1f69102f79935b1a0d0b344a06fae560c4cb68107d4eaff6de5f70969ace515ca0d7799b2f5d55d04dd1dbb9b5ec80ba

test:
  secret_key_base: 9182d7fe061fa35dccd78e4664d86cae57f301076d09562fbcc69f348f867566440d8882dc5c39613506a84cdd32420f967a8645f5e1eaaeb781df0212f7a223

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
